unique_ids:
  assets:
    standard-page.html: RIYUVTZL2EWUTSXCNWNPKO5KBS5D4HEW
    theme.css: FCXMWOUDEE627EMAJEUTBPNKXSXS6HLE
  forms:
    Form1: VRYQKTQYOKZET3MVUTUHHUYDMQPVP7XN
  modules: {}
  scripts: {}
  server_modules: {}
